###############################################################################
#
# Copyright (c) 2018, Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

image:
  # VS 2013 doesn't support C++14, so it doesn't compile.
  #- Visual Studio 2013
  - Ubuntu
  - Visual Studio 2015
  - Visual Studio 2017

clone_folder: c:\projects\yarpgen

configuration: Release

environment:
  matrix:
    - cmake_arch: x86
    - cmake_arch: x64

for:
-
  matrix:
    only:
      - image: Ubuntu

  clone_folder: ~/yarpgen
  build_script:
    - echo Ubuntu build script
    - mkdir build; cd build
    - cmake -DCMAKE_BUILD_TYPE=Release $extra_cmake_flags ..
    - make -j2
 
# skip unsupported combinations
init:
  - cmd: set arch=
  - cmd: if "%cmake_arch%"=="x64" ( set arch= Win64)
  - cmd: echo %arch%
  - cmd: echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
  - cmd: echo %generator%
  - sh: if [ "$cmake_arch" = "x86" ]; then export extra_cmake_flags=-DCMAKE_CXX_FLAGS=-m32; sudo apt-get update; sudo apt-get install -y g++-multilib; fi;

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%

build:
  project: c:\projects\yarpgen\build\YARPGen.sln
  verbosity: minimal
  parallel: true

